### PR TITLE
fix: rename override -> override_existing in UserBatch.cs

### PR DESCRIPTION
**Pull request by sinapy**
"override" is the incorrect variable name when using UpsertUsersAsync api. Instead "override_existing" should be used

### CODE REVIEW

**Comment by sinapy** [comment]
@JimmyPettersson85 , @itsmeadi , could you take a look?

**Comment by sinapy** [comment]
Thanks @JimmyPettersson85 . Can this PR be merged?

**Comment by JimmyPettersson85** [comment]
> Thanks @JimmyPettersson85 . Can this PR be merged?

yes, I was waiting for the tests to be run, not sure why nothing happens. Can you try to remove @itsmeadi as reviewer?

**Comment by sinapy** [comment]
I don't have the option to remove @itsmeadi from the reviewers. When I raised the PR, both code owners were assigned to review it automatically.

**Comment by JimmyPettersson85** [comment]
merged, will create a new release

**Pull request merged**
