### PR TITLE
Socket Exhaustion Fix

### PR DESCRIPTION
**Pull request by hoelter**
Creating a new HttpClient for every request can lead to socket exhaustion. This slight modification will mitigate this issue. More info can be found here: https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netcore-1.0

### CODE REVIEW

**Comment by tbarbugli** [comment]
thank you for the PR 👍

**Comment by hoelter** [comment]
Further note on this change: a static HttpClient is a simple change to mitigate socket exhaustion in this setup but does introduce a potential for problems with DNS changes depending on an end users setup with this SDK. More work could be done to improve that here. Taking it a step further however, ideally an end user could supply their own HttpClient to be used and have full control over its lifecycle.

**Comment by glitch100** [comment]
I think there are some changes to be made here still - I will get a branch up 👍

**Review by ferhatelmas — APPROVED** [review]
LGTM

**Comment by ferhatelmas** [comment]
@hoelter thanks :+1: 

@glitch100 please feel free to improve further :pray:

**Pull request merged**
