### PR TITLE
Add possibility to query enriched activities by ids

### PR DESCRIPTION
**Pull request by Solstice1557**
Hello,

I wanted to add possibility to query enriched activities by ids like in other clients (for example JS client).

Thank you

### CODE REVIEW

**Comment by ferhatelmas** [comment]
We will try to include it into a release today

**Review by peterdeme — APPROVED** [review]
lgtm

**Comment by peterdeme** [comment]
@Solstice1557 We did a small rework of your feature, but we just released it as 4.6.0: https://www.nuget.org/packages/stream-net/

**Comment by Solstice1557** [comment]
@peterdeme @ferhatelmas Thank you very much.

**Pull request merged**
