### PR TITLE
fix: send flattened data when upserting

### PR DESCRIPTION
**Pull request by peterdeme**

### CODE REVIEW

**Comment by ferhatelmas** [comment]
@peterdeme CI isn't happy

**Comment by peterdeme** [comment]
@ferhatelmas fixed

**Review by ferhatelmas — APPROVED** [review]
LGTM

**Comment by ferhatelmas** [comment]
interface is breaking though, what is the adaptation status?

**Comment by peterdeme** [comment]
@ferhatelmas quite a few downloads already https://www.nuget.org/stats/packages/stream-net?groupby=Version

**Comment by ferhatelmas** [comment]
let's major then

**Pull request merged**
